// Generated by gencpp from file proboscis_detection/robot_state_info.msg
// DO NOT EDIT!


#ifndef PROBOSCIS_DETECTION_MESSAGE_ROBOT_STATE_INFO_H
#define PROBOSCIS_DETECTION_MESSAGE_ROBOT_STATE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace proboscis_detection
{
template <class ContainerAllocator>
struct robot_state_info_
{
  typedef robot_state_info_<ContainerAllocator> Type;

  robot_state_info_()
    : tracking(0)
    , mosquito(0)  {
    }
  robot_state_info_(const ContainerAllocator& _alloc)
    : tracking(0)
    , mosquito(0)  {
  (void)_alloc;
    }



   typedef int32_t _tracking_type;
  _tracking_type tracking;

   typedef int32_t _mosquito_type;
  _mosquito_type mosquito;





  typedef boost::shared_ptr< ::proboscis_detection::robot_state_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proboscis_detection::robot_state_info_<ContainerAllocator> const> ConstPtr;

}; // struct robot_state_info_

typedef ::proboscis_detection::robot_state_info_<std::allocator<void> > robot_state_info;

typedef boost::shared_ptr< ::proboscis_detection::robot_state_info > robot_state_infoPtr;
typedef boost::shared_ptr< ::proboscis_detection::robot_state_info const> robot_state_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proboscis_detection::robot_state_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proboscis_detection::robot_state_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace proboscis_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'proboscis_detection': ['/home/administer/mosquitoes_project_ws/src/proboscis_detection/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::proboscis_detection::robot_state_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proboscis_detection::robot_state_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proboscis_detection::robot_state_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proboscis_detection::robot_state_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proboscis_detection::robot_state_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proboscis_detection::robot_state_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proboscis_detection::robot_state_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3462d490b19f22662965869fa73aeb01";
  }

  static const char* value(const ::proboscis_detection::robot_state_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3462d490b19f2266ULL;
  static const uint64_t static_value2 = 0x2965869fa73aeb01ULL;
};

template<class ContainerAllocator>
struct DataType< ::proboscis_detection::robot_state_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proboscis_detection/robot_state_info";
  }

  static const char* value(const ::proboscis_detection::robot_state_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proboscis_detection::robot_state_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 tracking\n\
int32 mosquito\n\
";
  }

  static const char* value(const ::proboscis_detection::robot_state_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proboscis_detection::robot_state_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tracking);
      stream.next(m.mosquito);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_state_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proboscis_detection::robot_state_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proboscis_detection::robot_state_info_<ContainerAllocator>& v)
  {
    s << indent << "tracking: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tracking);
    s << indent << "mosquito: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mosquito);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOSCIS_DETECTION_MESSAGE_ROBOT_STATE_INFO_H
